services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: macrofacts
      POSTGRES_USER: macrofacts
      POSTGRES_PASSWORD: macrofacts
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U macrofacts -d macrofacts"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: ./macrofacts-backend
    restart: unless-stopped
    environment:
      PORT: "8080"
      DATABASE_URL: postgresql://macrofacts:macrofacts@postgres:5432/macrofacts?sslmode=disable
      JWT_SECRET: change-me-super-long
      MONGO_URI: mongodb://mongo:27017
      OFF_DB: off
      OFF_COLLECTION: products
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy

  web:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./macrofacts-frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose:
      - "3000"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - web
      - api
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mongo:
    image: mongo:7
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: openfoodfacts
      MONGO_URI: mongodb://mongo:27017
      OFF_DB: off
      OFF_COLLECTION: products
    volumes:
      - off_mongo_data:/data/db      
      - ./openfoodfacts-dump:/openfoodfacts-dump:ro
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "mongodb://localhost:27017/openfoodfacts", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 3s
      retries: 30

 

volumes:
  pg_data:
  off_mongo_data: